version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t lautre/docker-mysql-wsrep:5.6 .
      - run: docker push lautre/docker-mysql-wsrep:5.6